[default]
extend-ignore-identifiers-re = [
    "AttributeID.*Supress.*",
]

[default.extend-identifiers]
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
# words that should not be corrected
Aer = "Aer"

[files]
extend-exclude = [
    ".gitignore",
    ".pre-commit-config.yaml"
]
